<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <?php if(!$has_session = session_status() == PHP_SESSION_ACTIVE)
    {
    session_start();
    }
    ?>
    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/css/bootstrap-theme.css" rel="stylesheet">
    <link href="/css/my-style.css" rel="stylesheet">
    <link href="/css/fonts.css" rel="stylesheet">
    <title>KRM Timesheet - <?php echo $view->pageTitle; ?></title>
</head>
<body>
<h1>KRM - Timesheet Manager</h1>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
<ul class="navbar navbar-expand-sm colour navbar-dark">
    <!-- Brand/logo -->
    <a class="navbar-brand">
        <img src="/images/krm-logo-1.png" alt="logo" style="width:100px;">
    </a>
    <!-- Links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="#">View Projects</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Upload Timesheet</a>
        </li>
    </ul>
    <ul class="nav navbar-nav navbar-right float-right">
        <?php
        if(isset($_SESSION['username']))
        {
            //echo 'Hello '. $_SESSION['user_name'];?>
            <li><a href="../../log_out.php"><span class="glyphicon glyphicon-log-out red"></span>Sign out</a></li>
        <?php }
        else
        {?>
        <?php } ?>
    </ul>
</ul>
    </div>
</nav>
        <div id="content">
        