<?php require('template/header.phtml') ?>
<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    <div>
        <label>Username:</label>
    <input required="required" class="form-control" type="text" name="user_name" placeholder="user name" value="">
        <?php if (isset($_POST['user_name']))
        ?>
    </div>
    <div>
        <label>Password:</label>
    <input required="required" class="form-control" type="password" name="user_pass" placeholder="password must be 8 characters long" value="">
        <?php if (isset($_POST['user_pass']))
        ?>
    </div>
    <div>
        <input type="submit" class="btn btn-primary btn-block" value="submit" name="submit">
    </div>
</form>
<?php require('template/footer.phtml') ?>