<?php require('template/header.phtml')?>
    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
        <div class="form-group">
            <label>Username:</label>
            <input required="required" class="form-control" type="text" name="user_name" placeholder="user name" value="">
            <?php if (isset($_POST['user_name']))
            {echo $_POST['user_name'];}
            ?>
        </div>
        <div class="form-group">
            <label>Password:</label>
            <input required="required" class="form-control" type="password" name="user_pass" placeholder="password must be 8 characters long" value="">
            <?php if (isset($_POST['user_pass']))
            ?>
        </div>
        <div class="form-group">
            <label>Password again:</label>
            <input required="required" class="form-control" type="password" name="user_pass_check" placeholder="Must match password" value="">
            <?php if (isset($_POST['user_pass_check']))
            ?>
        </div>
        <div class="form-group">
            <label>E-mail:</label>
            <input required="required" class="form-control" type="email" name="user_email" placeholder="example: E-Maill@address.com" value="">
            <?php if (isset($_POST['user_email']))
            ?>
        </div>

        <div>
            <p></p>
            <input type="submit" class="btn btn-primary btn-block" value="submit" name="submit">
        </div>
    </form>
<?php require('template/footer.phtml') ?>
