<?php require('template/header.phtml') ?>
<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    <div>
    <label>Project Name:</label>
    <input required="required" class="form-control" type="text" name="projectName" placeholder="Name Of The Project" value="">
<?php if (isset($_POST['projectName'])) ?>
    </div>
    <p></p>
    <div>
    <label>Client Name:</label>
    <input required="required" class="form-control" type="text" name="clientName" placeholder="Name Of The Client" value="">
<?php if (isset($_POST['clientName'])) ?>
    </div>
    <p></p>
    <div>
    <div class="form-group">
        <label for="usernames">Usernames:</label>
        <textarea class="form-control" rows="5" id="usernames" name="usernames"  type="text" placeholder="e.g username1, username2"></textarea>
    </div>
<?php if (isset($_POST['usernames'])) ?>
    </div>
    <p></p>
    <div>
        <input type="submit" class="btn btn-primary btn-block" value="submit" name="submit">
    </div>
    </form>
<?php require('template/footer.phtml') ?>