<?php require('template/header.phtml') ?>
    <h2><?php echo 'Hello '. $_SESSION['username'];?></h2>
    <thead>
        <h3>My Projects</h3>
    <p></p>
        </thead>
        <tbody>
        <button type="button" class="collapsible">View user's in this project</button>
        <div class="content">
            <div class="form-group">
                <p></p>
                <?php
                $test = $view->test;
                foreach ($test as $user){?>
                    <tr><td><p><?php echo $user->getFirstName(); echo " "; echo $user->getLastName()?></p></td></tr>
                <?php }?>
            </div>
        </div>
        <p></p>
        <button type="button" class="collapsible">Upload Timesheet</button>
        <div class="content">
            <div class="form-group">
        <div class="row d-flex justify-content-center mt-100">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h5>File Upload</h5>
                    </div>
                    <div class="card-block">
                        <form action="/Controller/parse_excel_file_modified.php" method="POST" enctype="multipart/form-data">
                            <div class="dz-default dz-message"><span>Drop files here to upload</span></div>
                            <br>
                            <input type="file" name="excel_file" style="border: 2px dashed #023A78; height: 120px; padding: 1rem" accept=".xlsx" value="">
                            <br>
                            <p></p>
                            <button class="btn1"><span class="glyphicon glyphicon-upload"></span> submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
            </div>
        </div>
        <?php  ?>
        <div class="chart-container">
            <canvas id="chart_0"></canvas>
        </div><?php
        $view->graphUserArray = $graphUserArray;
        foreach ($graphUserArray as $userGraph){?>
        <tr><td><p><?php //echo $user->getFirstName(); echo " "; echo $user->getLastName()?></p></td></tr>

        <script src="/js/Chart.min.js"></script>
        <script>
            var data = {
                labels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
                datasets: [{
                    label: "worked hours",
                    backgroundColor: "rgba(2,58,120,0.2)",
                    borderColor: "rgba(2,58,120,1)",
                    borderWidth: 1,
                    hoverBackgroundColor: "rgba(245,130,12,0.4)",
                    hoverBorderColor: "rgba(245,130,12,1)",
                    data: [<?php $userTimeArray;?>], //get the values from the controller
                }]
            };

            var option = {
                scales: {
                    yAxes: [{
                        stacked: true,
                        gridLines: {
                            display: true,
                            color: "rgba(102,102,102,0.2)"
                        }
                    }],
                    xAxes: [{
                        gridLines: {
                            display: false
                        }
                    }]
                }
            };

            Chart.Bar('chart_0', {
                options: option,
                data: data
            });
            window.onload = function() {
                var ctx = document.getElementById('chart_0').getContext('2d');
                window.myBar = new Chart(ctx, {
                    type: 'bar',
                    data: barChartData,
                    options: {
                        responsive: true,
                        legend: {
                            position: 'top',
                        },
                        title: {
                            display: true,
                            text: 'Chart.js Bar Chart'
                        }
                    }
                });

            };
        </script>
        <?php }?>
        </tbody>
<?php require('template/footer.phtml')?>