<?php require('template/header.phtml') ?>
    <h3><?php echo 'Hello '. $_SESSION['username'];?></h3>
    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
        <thead>
        <tr><th><h1>My Projects</h1></th></tr>
        </thead>
        <tbody>
    <button type="button" class="collapsible">View user's in this project</button>
<div class="content">
    <div class="form-group">

    </div>
</div>
    <p></p>
    <div>
        <button type="button" class="collapsible">Upload Timesheet</button>
        <div class="content">
            <div class="form-group">
        <div class="row d-flex justify-content-center mt-100">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h5>File Upload</h5>
                    </div>
                    <div class="card-block">
                        <form action="#" class="dropzone dz-clickable">
                            <div class="dz-default dz-message"><span>Drop files here to upload</span></div>
                        </form>
                        <div class="text-center m-t-20">
                            <button class="btn btn-primary">Upload Now</button>
                        <p></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            </div>
        </div>
        <canvas id="myChart" width="400" height="400"></canvas>
        <script>
            var ctx = document.getElementById('myChart').getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
                    datasets: [{
                        label: '# of Votes',
                        data: [12, 19, 3, 5, 2, 3],
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });
        </script>
        <button class="btn btn-primary">Download Timesheet </button>
        </tbody>
    </form>
<?php require('template/footer.phtml')?>