<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <?php if(!$has_session = session_status() == PHP_SESSION_ACTIVE)
    {
    session_start();
    }
    ?>
    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/css/bootstrap-theme.css" rel="stylesheet">
    <link href="/css/my-style.css" rel="stylesheet">
    <link href="/css/fonts.css" rel="stylesheet">
    <title>KRM Timesheet - <?php echo $view->pageTitle; ?></title>
</head>
<body>
<h1>KRM - Timesheet Manager</h1>

<nav class="navbar navbar-expand-lg navbar-dark colour" style="margin:24px 0;">
    <a class="navbar-brand">
        <img src="/images/krm-logo-1.png" alt="logo" style="width:100px;">
    </a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navb">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navb">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="javascript:void(0)">Create a project</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="javascript:void(0)">Link</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="javascript:void(0)">Disabled</a>
            </li>
        </ul>
        <?php
        if($has_session = session_status() == PHP_SESSION_ACTIVE) // checks for active session
        {
            if ($_SESSION['userLevel'] == 1) //checks if user is admin
            {
                ?>
                <a href="../../sign-up.php">Register a user</a>
            <?php
            } else {
            }
        }
        if(isset($_SESSION['username']))
        {?>
            <a href="../../log_out.php"><span class="glyphicon glyphicon-log-out red"></span>Sign out</a>
        <?php }
        else
        {
         } ?>
    </div>
</nav>
        <div id="content">
        